// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-8lLPlLQ2C_FvHu38UnIqqYww7FOVTSA',
    appId: '1:758054291669:web:12ab88eb940eaf66faba5c',
    messagingSenderId: '758054291669',
    projectId: 'test-f4851',
    authDomain: 'test-f4851.firebaseapp.com',
    storageBucket: 'test-f4851.firebasestorage.app',
    measurementId: 'G-5BDPPG3H9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSLbwwoDYBRk2yzHx3StefdGy7C3qQkZA',
    appId: '1:758054291669:android:c54dac3d9982fb9dfaba5c',
    messagingSenderId: '758054291669',
    projectId: 'test-f4851',
    storageBucket: 'test-f4851.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGI8Hz1fH1nFM36h_uyHB7f_5Jdyl3ElQ',
    appId: '1:758054291669:ios:b4ac46176e0ff60ffaba5c',
    messagingSenderId: '758054291669',
    projectId: 'test-f4851',
    storageBucket: 'test-f4851.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGI8Hz1fH1nFM36h_uyHB7f_5Jdyl3ElQ',
    appId: '1:758054291669:ios:b4ac46176e0ff60ffaba5c',
    messagingSenderId: '758054291669',
    projectId: 'test-f4851',
    storageBucket: 'test-f4851.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-8lLPlLQ2C_FvHu38UnIqqYww7FOVTSA',
    appId: '1:758054291669:web:81315bf6f3c35493faba5c',
    messagingSenderId: '758054291669',
    projectId: 'test-f4851',
    authDomain: 'test-f4851.firebaseapp.com',
    storageBucket: 'test-f4851.firebasestorage.app',
    measurementId: 'G-4KV1QR6XBL',
  );
}
